# Generated by Django 3.0.6 on 2020-05-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ユーザID')),
                ('name', models.CharField(max_length=20, verbose_name='ユーザ名')),
                ('description', models.CharField(max_length=100, verbose_name='紹介文')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id_voice', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ボイスID')),
                ('message', models.CharField(max_length=100, null=True, verbose_name='メッセージ')),
                ('good', models.IntegerField(default=0, verbose_name='いいね')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User', verbose_name='投稿者')),
            ],
            options={
                'db_table': 'voice',
            },
        ),
    ]
