# Generated by Django 3.0.6 on 2020-05-29 10:01

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='good',
            new_name='like',
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(null=True, upload_to=main.models.get_upload_to, verbose_name='アイコン'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='main.User')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='main.User')),
            ],
        ),
    ]
