# Generated by Django 3.0.6 on 2020-05-29 10:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200529_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_upload_to, verbose_name='アイコン'),
        ),
    ]
