# Generated by Django 3.0.6 on 2020-05-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200529_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='id_voice',
            new_name='voice_id',
        ),
    ]
